services:
  llmproxy:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    #volumes:
    #  - .:/app
    ports:
      - "4000:4000"
    env_file:
      - ".env"
    container_name: bn-router
    networks:
      - langfuse_default

#  tigerbeetle:
#    image: ghcr.io/tigerbeetle/tigerbeetle:0.16.49 # Or a specific version like :0.16.40
#    command: "start --cache-grid=256MiB --addresses=0.0.0.0:3033 /data/0_0.tigerbeetle"
#    cap_add:
#      - IPC_LOCK # Required for TigerBeetle's performance and safety
#    ports:
#      - "3033:3033"
#    security_opt:
#      - "seccomp=unconfined"
#    volumes:
#      - "./data:/data" # Persist data outside the container

networks:
  langfuse_default:
    external: true

