services:
  llmproxy:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    #volumes:
    #  - .:/app
    ports:
      - "4000:4000"
    env_file:
      - ".env"
    container_name: bn-router
    networks:
      - langfuse_default

networks:
  langfuse_default:
    external: true
